### ISSUE TITLE
Porting to Python 3.x and arm-none-eabi-gcc > v9.3.1-1.4 

### ISSUE THREAD

**Issue by vakochetkov** [in4lio/mdr1986x-JFlash#2]
Hello!
For some reason I have to use python 3.x, not 2.7. At least it's 2021 and 2.x python is deprecated and no longer supported.
So, I had to make some modifications to your script. 
1. python we use is WinPython 3.8.5
2. arm-none-eabi-gdb-py2 become arm-none-eabi-gdb-py3 and now is compiled with python 3.7 since 9.3.1 (now eclipse cmd is ${cross_prefix}gdb-py3${cross_suffix})
3. format of .map file was changed, so I have to edit your regexp in mapper
4. both mapper and jflash was converted by https://pythonconverter.com/ (2to3 library) to be sure everything alright with code (it is)
5. rebuild loaders for arm-none-eabi-gcc 9.3.1

That's all! Everything works as expected. 
Now, the question. Are you able to merge it with your repo or should I fork your repo or create my own?

**Comment by in4lio** [comment]
Hi @vakochetkov,

Thank you for the message. Please prepare a pull request if possible. Unfortunately, at the moment, I can't test this script.

**Comment by vakochetkov** [comment]
The problem is both mapper.py and JFlash.py was changed. as well as LOADER. I think it should be in the separate folder. I will create PR ASAP.

**Comment by in4lio** [comment]
Merged. Thank you!
